# Generated by Django 5.1.7 on 2025-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('qna', 'Q&A'), ('cheer', 'Praise & Cheer')], default='feedback', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
