# Generated by Django 5.1.7 on 2025-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_updated_at_post_type_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('feedback', 'Feedback'), ('qna', 'Q&A'), ('cheer', 'Praise & Cheer')], max_length=10),
        ),
    ]
