# Generated by Django 5.1.7 on 2025-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('djgnfj', 'Djgnfj'), ('guest', 'Guest')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='guest_0000', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
